language: php

php:
  - 5.4
  - 5.5

install:
  - composer self-update
  - composer install --dev --no-progress
  - npm install -g bower

before_script: mysql -e 'create database testing;'

script: ./vendor/bin/codecept run unit