language: php

php:
  - 5.4
  - 5.5

install:
  - composer self-update
  - npm install -g bower
  - composer install --dev --no-progress
  - touch ./tests/_localurl.php
  - echo "<?php return '/web/index-test.php';" >> ./tests/codeception/_localurl.php
  - 'cd tests && ./../vendor/bin/codecept build'

before_script: mysql -e 'create database testing;'

script: './../vendor/bin/codecept run unit'